services:
  frontend:
    image: front:v1
    build: ./frontend/
    ports:
      - "3000:3000"
    networks:
      - tran_network
    restart: always

  backend:
    image: back:v1
    build: ./backend/
    ports:
      - "8000:8000"
    networks:
      - tran_network
    depends_on:
      - frontend
    restart: always

networks:
  tran_network:
    driver: bridge

